export const PRODUCT_POST_PENDING = 'PRODUCT_POST_PENDING';
export const PRODUCT_POST_FULFILLED = 'PRODUCT_POST_FULFILLED';
export const PRODUCT_POST_REJECTED = 'PRODUCT_POST_REJECTED';

export const PRODUCT_PUT_PENDING = 'PRODUCT_PUT_PENDING';
export const PRODUCT_PUT_FULFILLED = 'PRODUCT_PUT_FULFILLED';
export const PRODUCT_PUT_REJECTED = 'PRODUCT_PUT_REJECTED';

export const PRODUCT_DELETE_PENDING = 'PRODUCT_DELETE_PENDING';
export const PRODUCT_DELETE_FULFILLED = 'PRODUCT_DELETE_FULFILLED';
export const PRODUCT_DELETE_REJECTED = 'PRODUCT_DELETE_REJECTED';

export const PRODUCT_ALL_PENDING = 'PRODUCT_ALL_PENDING';
export const PRODUCT_ALL_FULFILLED = 'PRODUCT_ALL_FULFILLED';
export const PRODUCT_ALL_REJECTED = 'PRODUCT_ALL_REJECTED';

export const PRODUCT_GET_PENDING = 'PRODUCT_GET_PENDING';
export const PRODUCT_GET_FULFILLED = 'PRODUCT_GET_FULFILLED';
export const PRODUCT_GET_REJECTED = 'PRODUCT_GET_REJECTED';

